kind: Secret
apiVersion: v1
metadata:
  name: git-credentials-secret
  labels:
    controller.devfile.io/git-credential: 'true'
    controller.devfile.io/watch-secret: 'true'
  annotations:
    controller.devfile.io/mount-path: /etc/secret
data:
  credentials: YourBase64GitFileCredentials ##Github plaintext value example: https://YourGitUsername:YourPATToken@github.com
type: Opaque
