kind: Secret
apiVersion: v1
metadata:
  name: devworkspace-container-registry-dockercfg
  labels:
    controller.devfile.io/devworkspace_pullsecret: 'true'
    controller.devfile.io/mount-to-devworkspace: 'true' # this will auto mount to: /etc/secret/devworkspace-container-registry-dockercfg/.dockerconfigjson
    controller.devfile.io/watch-secret: 'true'
data:
  # This is base64 encoded for: {  "auths": {    "yourRegistry.com": {      "auth": "yourAuthToken",      "email": ""    }  }}
  #
  .dockerconfigjson: eyAgImF1dGhzIjogeyAgICAieW91clJlZ2lzdHJ5LmNvbSI6IHsgICAgICAiYXV0aCI6ICJ5b3VyQXV0aFRva2VuIiwgICAgICAiZW1haWwiOiAiIiAgICB9ICB9fQ==
type: kubernetes.io/dockerconfigjson
